mongodb:
  uri: "mongodb://localhost:27017"
  database: "crawler"
  collections:
    crawl_results: "crawl_results"
    url_fingerprints: "url_fingerprints"

# HTTP Fetcher Configuration
fetcher:
  user_agent: "AxoraCrawler/1.0 (+https://axora.com/crawler)"
  timeout: 30
  max_retries: 3
  retry_delay: 1
  max_redirects: 5
  max_response_size: 10485760  # 10MB

# Politeness Configuration
politeness:
  default_delay: 1.0  # seconds between requests to same host
  respect_robots_txt: true
  robots_cache_ttl: 3600  # seconds

# URL Processing
url_processing:
  allowed_schemes: ["http", "https"]
  max_url_length: 2048
  normalize_urls: true

# Crawler Behavior
crawler:
  max_claim_duration: 300  # seconds before URL claim expires
  worker_loop_delay: 0.1  # seconds between worker iterations
  batch_size: 10