version: '3.5'

services:
  axora-minilml6v2:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    container_name: axora-minilml6v2
    restart: unless-stopped
    environment:
      - MODEL_ID=sentence-transformers/all-MiniLM-L6-v2
      - PORT=8000
      - MAX_CONCURRENT_REQUESTS=4
      - MAX_BATCH_TOKENS=1024
      - MAX_BATCH_REQUESTS=8
      - NUM_SHARD=1
      - CUDA_VISIBLE_DEVICES=""
      - HUGGING_FACE_HUB_TOKEN=""
    ports:
      - "8000:8000"
    volumes:
      - axora-minilml6v2-cache:/data
    networks:
      - axora-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  axora-crawler:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: axora-crawler
    restart: unless-stopped
    environment:
      APP_PORT: ${APP_PORT}
      SERP_API_KEY: ${SERP_API_KEY}
      TEI_MODEL_CLIENT_URL: ${TEI_MODEL_CLIENT_URL}
      QDRANT_HTTP_PORT: ${QDRANT_HTTP_PORT}
      QDRANT_GRPC_PORT: ${QDRANT_GRPC_PORT}
      QDRANT_HOST: ${QDRANT_HOST}
      MINILML6V2_URL: ${MINILML6V2_URL}
      DOCKER_BUILDKIT: 1
    ports:
      - "${APP_PORT}:8080"
    networks:
      - axora-network
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 512M
  
  qdrant:
    container_name: axora-qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - axora-network

volumes:
  qdrant_storage:
  axora-minilml6v2-cache:

networks:
  axora-network:
    driver: bridge