version: '3.8'

services:
  axora-model-service:
    image: ghcr.io/huggingface/text-embeddings-inference:1.5
    container_name: axora-model-service
    restart: unless-stopped
    environment:
      - MODEL_ID=sentence-transformers/all-MiniLM-L6-v2
      - PORT=80
      - MAX_CONCURRENT_REQUESTS=512
      - MAX_BATCH_TOKENS=16384
    ports:
      - "8000:80"
    volumes:
      - axora-model-cache:/data
    networks:
      - axora-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  axora-mongodb:
    image: mongo:latest
    container_name: axora-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - axora-mongodb-data:/data/db
    networks:
      - axora-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  axora-mongo-express:
    image: mongo-express:latest
    container_name: axora-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    depends_on:
      axora-mongodb:
        condition: service_healthy
    networks:
      - axora-network

  axora-crawler:
    build: 
      context: .
      dockerfile: Dockerfile
      cache_from:
        - axora-crawler:latest
    container_name: axora-crawler
    restart: unless-stopped
    environment:
      MONGO_URL: ${MONGO_URL}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_EXPRESS_USERNAME: ${MONGO_EXPRESS_USERNAME}
      MONGO_EXPRESS_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      MONGO_EXPRESS_PORT: ${MONGO_EXPRESS_PORT}
      APP_PORT: ${APP_PORT}
      SERP_API_KEY: ${SERP_API_KEY}
      MODEL_SERVICE_URL: http://axora-model-service:80
      DOCKER_BUILDKIT: 1
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      axora-model-service:
        condition: service_healthy
      axora-mongodb:
        condition: service_healthy
    networks:
      - axora-network

volumes:
  axora-mongodb-data:
  axora-model-cache:

networks:
  axora-network:
    driver: bridge