version: '3.8'

services:
  axora-mongodb:
    image: mongo:latest
    container_name: axora-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - axora-mongodb-data:/data/db
    networks:
      - axora-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  axora-mongo-express:
    image: mongo-express:latest
    container_name: axora-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    depends_on:
      axora-mongodb:
        condition: service_healthy
    networks:
      - axora-network

  axora-crawler:
    build: 
      context: .
      dockerfile: Dockerfile
      cache_from:
        - axora-crawler:latest
    container_name: axora-crawler
    environment:
      MONGO_URL: ${MONGO_URL}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_EXPRESS_USERNAME: ${MONGO_EXPRESS_USERNAME}
      MONGO_EXPRESS_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      MONGO_EXPRESS_PORT: ${MONGO_EXPRESS_PORT}
      APP_PORT: ${APP_PORT}
      SERP_API_KEY: ${SERP_API_KEY}
      DOCKER_BUILDKIT: 1
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      axora-mongodb:
        condition: service_healthy
    networks:
      - axora-network

volumes:
  axora-mongodb-data:

networks:
  axora-network:
    driver: bridge