version: '3.5'

services:

  axora-crawler:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: axora-crawler
    environment:
      APP_PORT: 8080
      PROXY_URL: http://axora-tor-proxy:3128
      POSTGRES_DB_URL: postgres://postgres:postgres@axora-postgres:5432/axora?sslmode=disable
      DOWNLOAD_PATH: /app/downloads
      DOCKER_BUILDKIT: 1
      KAFKA_URL: axora-kafka:9092
      QDRANT_HTTP_PORT: 6333
      QDRANT_GRPC_PORT: 6334
      QDRANT_HOST: axora-qdrant
    ports:
      - "8080:8080"
    networks:
      - axora-network
    volumes:
      - ./downloads:/app/downloads
      - ./domains.yaml:/app/domains.yaml
    depends_on:
      axora-postgres:
        condition: service_healthy
      axora-tor-proxy:
        condition: service_started
      axora-kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 3G
        reservations:
          cpus: '1.0' 
          memory: 1G

  axora-tor-proxy:
    image: zhaowde/rotating-tor-http-proxy
    container_name: axora-tor-proxy
    ports:
      - "3128:3128"
    environment:
      TOR_INSTANCES: 10
      TOR_REBUILD_INTERVAL: 600
      TOR_EXIT_COUNTRY: jp,tw,th,id,sg
    networks:
      - axora-network

networks:
  axora-network:
    driver: bridge

volumes:
  postgres_data:
  kafka_data: