version: '3.5'

services:
  axora-mpnetbasev2:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    container_name: axora-mpnetbasev2
    environment:
      - MODEL_ID=sentence-transformers/all-mpnet-base-v2
      - PORT=8000
      - MAX_CONCURRENT_REQUESTS=100
      - MAX_BATCH_TOKENS=4096
      - MAX_BATCH_REQUESTS=64
      - NUM_SHARD=1
      - CUDA_VISIBLE_DEVICES=""
      - HUGGING_FACE_HUB_TOKEN=""
    ports:
      - "8000:8000"
    volumes:
      - axora-mpnetbasev2-cache:/data
    networks:
      - axora-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  axora-crawler:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: axora-crawler
    environment:
      APP_PORT: 8080
      QDRANT_HTTP_PORT: ${QDRANT_HTTP_PORT}
      QDRANT_GRPC_PORT: ${QDRANT_GRPC_PORT}
      QDRANT_HOST: ${QDRANT_HOST}
      MPNETBASEV2_URL: ${MPNETBASEV2_URL}
      CHUNKING_URL: ${CHUNKING_URL}
      TOR_PROXY_URL: ${TOR_PROXY_URL}
      TOR_CONTROL_URL: ${TOR_CONTROL_URL}
      DOWNLOAD_PATH: ${DOWNLOAD_PATH}
      DOCKER_BUILDKIT: 1
    ports:
      - "8080:8080"
    volumes:
      - ./downloads:${DOWNLOAD_PATH}
    networks:
      - axora-network
    depends_on:
      axora-mpnetbasev2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 512M

  axora-qdrant:
    container_name: axora-qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=${QDRANT_HTTP_PORT}
      - QDRANT__SERVICE__GRPC_PORT=${QDRANT_GRPC_PORT}
    networks:
      - axora-network

  axora-semantic-chunker:
    build: 
      context: ./model
      dockerfile: Dockerfile.pithon
    container_name: axora-semantic-chunker
    ports:
      - "8001:8001"
    environment:
      - MPNETBASEV2_URL=${MPNETBASEV2_URL}
    depends_on:
      axora-mpnetbasev2:
        condition: service_healthy
    networks:
      - axora-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M

  axora-tor:
    image: dperson/torproxy
    container_name: axora-tor
    volumes:
      - ./torrc:/etc/tor/torrc:ro
    networks:
      - axora-network
    ports:
      - "9050:9050"

  tor-control-bridge:
    image: alpine/socat
    container_name: tor-control-bridge
    command: tcp-listen:9051,fork,reuseaddr tcp-connect:axora-tor:9051
    networks:
      - axora-network
    ports:
      - "9051:9051"
    depends_on:
    - axora-tor

volumes:
  qdrant_storage:
  axora-mpnetbasev2-cache:

networks:
  axora-network:
    driver: bridge