version: '3.5'

services:

  axora-crawler:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: axora-crawler
    environment:
      APP_PORT: 8080
      PROXY_URL: http://axora-tor-proxy:3128
      DOCKER_BUILDKIT: 1
    ports:
      - "8080:8080"
    networks:
      - axora-network
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  axora-tor-proxy:
    image: zhaowde/rotating-tor-http-proxy
    container_name: axora-tor-proxy
    ports:
      - "3128:3128"
    environment:
      TOR_INSTANCES: 30
      TOR_REBUILD_INTERVAL: 600
      TOR_EXIT_COUNTRY: jp,tw,th,id,sg
    networks:
      - axora-network

networks:
  axora-network:
    driver: bridge