services:
  axora-tei-model:
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    container_name: axora-tei-model
    restart: unless-stopped
    environment:
      - ENABLE_CUDA=0  # Set to 1 if you have GPU support
    ports:
      - "8080:8080"  # Weaviate transformers-inference uses port 8080 internally
    volumes:
      - axora-model-cache:/data
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - axora-network

  axora-mongodb:
    image: mongo:latest
    container_name: axora-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - axora-mongodb-data:/data/db
    networks:
      - axora-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  axora-mongo-express:
    image: mongo-express:latest
    container_name: axora-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    networks:
      - axora-network

  axora-crawler:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: axora-crawler
    restart: unless-stopped
    environment:
      MONGO_URL: ${MONGO_URL}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_EXPRESS_USERNAME: ${MONGO_EXPRESS_USERNAME}
      MONGO_EXPRESS_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      MONGO_EXPRESS_PORT: ${MONGO_EXPRESS_PORT}
      APP_PORT: ${APP_PORT}
      SERP_API_KEY: ${SERP_API_KEY}
      TEI_MODEL_CLIENT_URL: ${TEI_MODEL_CLIENT_URL}
      WEAVIATE_URL: ${WEAVIATE_URL}
      DOCKER_BUILDKIT: 1
    ports:
      - "${APP_PORT}:8000"
    networks:
      - axora-network
    depends_on:
      axora-mongodb:
        condition: service_healthy
      axora-weaviate:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 512M

  axora-weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8082'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
    container_name: axora-weaviate
    restart: unless-stopped
    ports:
      - 8082:8082
      - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://axora-tei-model:8080'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - axora-weaviate-data:/var/lib/weaviate
    networks:
      - axora-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
        reservations:
          cpus: '1.0'
          memory: 2G
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8082"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  axora-weaviate-console:
    image: semitechnologies/weaviate-console:latest
    container_name: axora-weaviate-console
    ports:
      - "8083:80"
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - axora-network
    depends_on:
      axora-weaviate:
        condition: service_healthy

volumes:
  axora-weaviate-data:
  axora-mongodb-data:
  axora-model-cache:

networks:
  axora-network:
    driver: bridge