POST http://localhost:8002/seed
Content-Type: application/json

{
  "topic": "economy",
  "chunking_method": "md"
}

POST http://localhost:8080/browse
Content-Type: application/json

{
  "topic": "economy",
  "chunking_method": "md"
}

curl -X POST http://localhost:8000/embed \
  -H "Content-Type: application/json" \
  -d '{"inputs": "What is artificial intelligence?"}'

curl -X POST "http://localhost:6333/collections/crawl_collection/points/search" \
     -H "Content-Type: application/json" \
     -d '{
           "vector": [],
           "limit": 5,
           "with_payload": true,
           "with_vector": false
         }'