# GET http://localhost:8080/browse?q=economy

# GET http://localhost:8080/seed

curl -X POST http://localhost:8000/embed \
  -H "Content-Type: application/json" \
  -d '{"inputs": "What is artificial intelligence?"}'

# curl -X POST "http://localhost:6333/collections/crawl_collection/points/search" \
#      -H "Content-Type: application/json" \
#      -d '{
#            "vector": [],
#            "limit": 5,
#            "with_payload": true,
#            "with_vector": false
#          }'