# Runtime configuration (politeness limits, allow/deny rules, 
# timeouts, Mongo connection strings, UA). 
# The app loads this at startup — no hardcoded values.

# Kafka Configuration
kafka:
  bootstrap_servers: "localhost:9092"
  topics:
    seed: "urls.seed"
    success: "urls.crawl.success"
    failed: "urls.crawl.failed"
  consumer:
    group_id: "crawler-workers"
    auto_offset_reset: "earliest"
    max_poll_records: 100
  producer:
    acks: "all"
    retries: 3

# MongoDB Configuration
mongodb:
  uri: "mongodb://localhost:27017"
  database: "crawler"
  collections:
    crawl_results: "crawl_results"
    url_fingerprints: "url_fingerprints"

# HTTP Fetcher Configuration
fetcher:
  user_agent: "AxoraCrawler/1.0 (+https://axora.com/crawler)"
  timeout: 30
  max_retries: 3
  retry_delay: 1
  max_redirects: 5
  max_response_size: 10485760  # 10MB

# Politeness Configuration
politeness:
  default_delay: 1.0  # seconds between requests to same host
  respect_robots_txt: true
  robots_cache_ttl: 3600  # seconds

# URL Processing
url_processing:
  allowed_schemes: ["http", "https"]
  max_url_length: 2048
  normalize_urls: true

# Crawler Behavior
crawler:
  max_claim_duration: 300  # seconds before URL claim expires
  worker_loop_delay: 0.1  # seconds between worker iterations
  batch_size: 10

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Metrics Configuration (optional)
metrics:
  enabled: true
  port: 8080